/* generated by Payload — admin root layout (don't edit) */
import "./custom.scss";
import { metadata } from "./metadata.jsx";
import React from "react";

export { metadata };

export default function RootLayout({ children }) {
  return <React.Fragment>{children}</React.Fragment>;
}
